#pragma config(Motor,  port2,           topmotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontleft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontright,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backright,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		motor[frontleft]=vexRT[Ch3];

		motor[backleft]=vexRT[Ch3];

		motor[frontright]=1*vexRT[Ch2];

		motor[backright]=1*vexRT[Ch2];

		//motor[topmotor]= vexRT[Btn7R];

		if(vexRT[Btn7R]==1)

		{
			motor[topmotor]=127;
		}
		motor[topmotor]=0;
	}
}
