#pragma config(Sensor, in1,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in2,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in3,    midLine,        sensorLineFollower)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           right1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           right2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           left2,         tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int lightThreshhold = 2000;
int speed = 25;

void tankDrive(int left, int right){
	motor[left1] = -left;
	motor[left2] = left;
	motor[right1] = right;
	motor[right2] = -right;
}

task main()
{
	while(true){
		int lightPattern = 0;

		if(SensorValue[leftLine] > lightThreshhold){
			lightPattern = lightPattern + 1;
		}
		else{
			lightPattern = lightPattern + 0;
		}

		if(SensorValue[midLine] > lightThreshhold){
			lightPattern = lightPattern + 2;
		}
		else{
			lightPattern = lightPattern + 0;
		}

		if(SensorValue[rightLine] > lightThreshhold){
			lightPattern = lightPattern + 4;
		}
		else{
			lightPattern = lightPattern + 0;
		}

		switch(lightPattern)
		{
			case(0):
				tankDrive(-speed,-speed);
				break;
			case(1):
				tankDrive(0,speed);
				break;
			case(2):
				tankDrive(speed,speed);
				break;
			case(3):
				tankDrive(-speed,speed);
				break;
			case(4):
				tankDrive(0,-speed);
				break;
			case(5):
				tankDrive(speed,speed);
				break;
			case(6):
				tankDrive(speed,-speed);
				break;
			case(7):
				tankDrive(speed,speed);
				break;
			default:
				tankDrive(0,0);
				break;
		}
	}
}
